#!/usr/bin/python

print('Hello Git!')
print('Watanabe Rui')
print('st15083')
print("���M�@�@��Y")
print("st15051")
print('Watanabe Rui')
print('Yoshioka Takashi')
print('08319390')
print('st19439')
print('Yamaji syuhei')
print('iwase')
print('st15049')
print('Watanabe Rui')
print('Yoshioka Takashi')
print('Oshima Fuga')
print('st19406')
print('d-kitamura')
print('Watanabe Rui')
print('Yoshioka Takashi')